version: "3"

services:
  db:
    image: mysql
    container_name: db_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/data/db
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    networks:
      - services-networks

  api:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/server
    environment:
      PORT: 3001
      MYSQL_URI: mysql://db:3306
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - services-networks

volumes:
  db: {}

networks:
  services-networks:
    driver: bridge
