version: "3"

services:
  db:
    image: mysql
    container_name: db_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - db:/data/db
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      SERVICE_NAME: db
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - services-networks

  api:
    build: .
    ports:
      - 3001:3001
    expose:
      - 3001
    volumes:
      - .:/usr/src/server
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: "root"
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3001
    depends_on:
      - db
    networks:
      - services-networks

volumes:
  db: {}

networks:
  services-networks:
    driver: bridge
